name: Deploy Next.js 15 to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build with export
      run: npm run build
      env:
        NEXT_PUBLIC_BASE_PATH: '/yigim-app'

    - name: Verify export files
      run: |
        echo "=== Export directory structure ==="
        ls -la
        echo "=== Looking for HTML files ==="
        find . -name "*.html" -type f
        echo "=== If using output: 'export', check default folder ==="
        ls -la out/ 2>/dev/null || echo "No out directory - checking .next"
        ls -la .next/ 2>/dev/null || echo "No .next directory"

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./.next # Или ./dist в зависимости от конфига

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4